### PR TITLE
Angular updates and support for typed forms

### PR DESCRIPTION
**Pull request by fgonzaleziv**
# Description

NPM updates for the angular client: #122 

## Purpose

- [ ] Feature
- [ ] Partial Feature
- [ ] Bugfix
- [ ] Docs, Config
- [X] Chore / Format

## Change Type

- [ ] Major
- [ ] Minor
- [X] Fix

## Data Persistence Changes

N/A

## Configuration Changes

Some changes were done to angular.json and style.scss to support updates.

Casting was implemented to the forms to support the typed form requirement for Angular 14

### CODE REVIEW

**Comment by KyleMcMaster** [comment]
Thanks for the contribution! I'll mark the PR hacktoberfest-accepted and will review when I have time. 😄

**Comment by KyleMcMaster** [comment]
Holding until build passes, will likely require additional changes

**Comment by fgonzaleziv** [comment]
The bootstrap 5 upgrade will take a bit more code changes (they renamed several classes that are used in the code) and another few package update so that it'll build.  I can take a look at later this week.

**Comment by KyleMcMaster** [comment]
Closing due to inactivity, please feel free to reopen if you'd like to complete this work.

**Pull request closed without merging**
